### ISSUE TITLE
Build Payments Portal ( a part of finance portal)

### ISSUE THREAD

**Issue by RohitB97** [RohitB97/saarang-portals#1]
Login into the portals and enter finance portal....the first tab will be the payments portal.
You need to build the UI of the portal ....we'll work on database integration once i configure the database
I'll discuss with you the portal functionality on whatsapp/gmail. The work progress will be followed on this issue.....so keep a track of the issue @smrutipatro

**Comment by RohitB97** [comment]
please acknowledge @smrutipatro

**Comment by smrutipatro** [comment]
Acknowledged

**Comment by RohitB97** [comment]
So you're work is to build a portal where the users can upload a PDF and all the uploaded PDFs should be displayed. The user should be able to view the PDF in a separate tab when he clicks it. @smrutipatro

**Comment by smrutipatro** [comment]
Uploaded button.html file which is the code for an animated button for uploading files. Also uploaded button1.html file which is a normal primary button. Choose one among them, as which is consistent with the layout of the entire portal. yes6.jpg is an image used in button.html file. Suggest changes needed to make, if any.

**Comment by smrutipatro** [comment]
As for displaying pdf files, it can be done via displaying links for the pdf files. Another way, to directly display the pdf files without clicking on links is to use view.box.com. They basically convert your given pdf file into a widget for convenient display over webpage. Reference link: https://view.box.com/reference#documents

**Comment by smrutipatro** [comment]
All of the above files, I have put it in Payment_Portal Folder. Or do I create a new branch and send pull request?

**Comment by RohitB97** [comment]
Your button should be a file upload input button not a link button...... @smrutipatro

**Comment by smrutipatro** [comment]
My bad!! Changed the code to a file upload button.

**Comment by smrutipatro** [comment]
Pushed the code for card.

**Comment by smrutipatro** [comment]
Read the Cloudinary documentation.

**Comment by RohitB97** [comment]
So did you understand ....how PDFs are uploaded to cloudinary ...did you read about the API ?

**Comment by smrutipatro** [comment]
Yeah I did. Uploading PDFs is very much similar to uploading images done through the standard upload API. Btw, why arent we using Cloudinary to generate images and thumbnails from the PDF files? We can then put them on the cards instead of the general PDF image. Reference: http://cloudinary.com/blog/uploading_converting_and_generating_thumbnails_for_pdf_documents

**Comment by smrutipatro** [comment]
Yeah I did. Uploading PDFs is very much similar to uploading images done
through the standard upload API. Btw, why arent we using Cloudinary to
generate images and thumbnails from the PDF files? We can then put them on
the cards instead of the general PDF image. Reference:
http://cloudinary.com/blog/uploading_converting_and_generating_thumbnails_for_pdf_documents

**Comment by RohitB97** [comment]
@smrutipatro add the cloudinary API code into $scope.uploadFiles function and use an argument to use $file......
The API url is **https://api.cloudinary.com/v1_1/gallerysaarang/upload**
upload_preset : **finance_data**
tags: **finance-data**

store the data.url in $scope.data.url ( we will use this object to put a post request to our database)

**Comment by RohitB97** [comment]
@smrutipatro refer app-portal code (main.js) if you doubts or contact me directly

**Comment by smrutipatro** [comment]
Added the Cloudinary API code. Didnt do the HTTP post request to database
since database url is required.

**Comment by RohitB97** [comment]
good work...will get back to you

**Comment by RohitB97** [comment]
@smrutipatro  add the Post request to our database 
the url is **https://data.saarang.org/v1/query**
just take a look at the bill object to understand in which table the row is created and what all columns are there...and also include config object to attach the auth token

**Comment by smrutipatro** [comment]
Added the HTTP get request

**Comment by RohitB97** [comment]
@smrutipatro good work with the payments portal.
The issue will be closed and will later be reopened in case the finance team reports bugs.
