### ISSUE TITLE
Build Prize Money Portal (part of Finance Portal)

### ISSUE THREAD

**Issue by RohitB97** [RohitB97/saarang-portals#2]
Login into the portals and enter finance portal....the second tab will be the prize money portal.
You need to build the UI of the portal ....we'll work on database integration once i configure the database
I'll discuss with you the portal functionality on whatsapp/gmail. The work progress will be followed on this issue.....so keep a track of the issue @neerajparmaar and please Acknowledge in the comment

**Comment by neerajparmaar** [comment]
Acknowledged

**Comment by RohitB97** [comment]
@neerajparmaar Your work is to design a form ( i'll tell you what all fields required) and once the user fills the form....a PDF should be generated containing all the information the user inputs and all those PDFs should be displayed on the portal

**Comment by RohitB97** [comment]
@neerajparmaar done with the two buttons ?

**Comment by neerajparmaar** [comment]
Updated ppm.html with 2 buttons one to download a blank excel sheet other to upload only excel sheets.
Added a new folder named files which contains a blank excel sheet.

**Comment by RohitB97** [comment]
@neerajparmaar If displaying excel sheets is tough....let's display cards with an excel sheet image and name below as the actual name of the sheet....make the card clickable and link it to the sheet

**Comment by neerajparmaar** [comment]
Centred the buttons, added input box, added <md-toolbar> and added bootstrap class for viewing cards as required.

**Comment by neerajparmaar** [comment]
* added toolbar and added ..

**Comment by RohitB97** [comment]
The bootstrap cards aren't there in the code you pushed ....just check your code @neerajparmaar

**Comment by neerajparmaar** [comment]
Added the cards

**Comment by RohitB97** [comment]
@neerajparmaar  add the cloudinary API code into $scope.uploadFiles function and use an argument to use $file......
The API url is **https://api.cloudinary.com/v1_1/gallerysaarang/upload**
upload_preset : **finance_data**
tags: **finance-data**

store the data.url in $scope.data.url ( we will use this object to put a post request to our database)

refer app-portal code and the code in payment.js

**Comment by neerajparmaar** [comment]
Updated with cloudinary API

**Comment by RohitB97** [comment]
Nice work....will get back to you

**Comment by RohitB97** [comment]
@neerajparmaar add the Post request to our database 
the url is **https://data.saarang.org/v1/query**
just take a look at the sheet object to understand in which table the row is created and what all columns are there...and also include config object to attach the auth token

**Comment by neerajparmaar** [comment]
Post request to database added.

**Comment by RohitB97** [comment]
@neerajparmaar Good work with the PPM portal.
The issue will be closed and will be later reopened in case the finance team reports bugs
