### ISSUE TITLE
Build Reimbursements Portal (a part of finance portal)

### ISSUE THREAD

**Issue by RohitB97** [RohitB97/saarang-portals#3]
Login into the portals and enter finance portal....the third tab will be the payments portal.
You need to build the UI of the portal ....we'll work on database integration once i configure the database
I'll discuss with you the portal functionality on whatsapp/gmail. The work progress will be followed on this issue.....so keep a track of the issue @retwick please Acknowledge in the comments

**Comment by retwick** [comment]
acknowledged

**Comment by RohitB97** [comment]
@retwick  Updates on the work ?

**Comment by RohitB97** [comment]
@retwick Please update me on your work ?

**Comment by retwick** [comment]
How about I add an linear progress bar to show while uploading the file? Implementing an indeterminate one would be easier.

**Comment by RohitB97** [comment]
Updates on the Chrome browser bug ? @retwick

**Comment by retwick** [comment]
w3schools suggest not to use 'accept' as a validation tool. 
Maybe a script could be written to check all extensions possible

**Comment by RohitB97** [comment]
So let's do it that way.....but for ppm portal....in chrome...is it showing excel sheets ?
