### ISSUE TITLE
Improve Login/SignUp Page design

### ISSUE THREAD

**Issue by RohitB97** [RohitB97/saarang-portals#4]
Search for Login/SignUp designs on google and visit multiple websites with top quality designing and come up with a professional and elegant design.
Make sure you nail the UI because this is going to be the first page a user sees.
Work progress will be tracked through comments ... please Acknowledge @revanthchandrag

**Comment by revanthchandrag** [comment]
Ok

**Comment by RohitB97** [comment]
@revanthchandrag Come up with a set of good designs by tomorrow....so that we can decide which one to implement and you can start off with the work

**Comment by RohitB97** [comment]
@revanthchandrag Did you come up with designs for the auth page ?

**Comment by RohitB97** [comment]
@revanthchandrag Updates ?

**Comment by revanthchandrag** [comment]
https://codepen.io/ehermanson/pen/KwKWEv

https://codepen.io/atakan/pen/gqbIz

https://codepen.io/afirulaf/pen/djAen

**Comment by RohitB97** [comment]
https://www.template.net/web-templates/htmlcss-templates/signup-form/

**Comment by revanthchandrag** [comment]
https://w3layouts.com/gaming-login-form-responsive-widget-template/

**Comment by revanthchandrag** [comment]
https://w3layouts.com/smart-login-form-responsive-widget-template/

**Comment by revanthchandrag** [comment]
https://w3layouts.com/preview/?l=/magical-login-form-flat-responsive-widget-template/

**Comment by RohitB97** [comment]
@revanthchandrag Updates on new design ?

**Comment by RohitB97** [comment]
@revanthchandrag Updates on the login form ?

**Comment by revanthchandrag** [comment]
I'm searching

**Comment by revanthchandrag** [comment]
I'm searching

On 04-Jun-2017 2:50 AM, "Rohit Bokam" <notifications@github.com> wrote:

@revanthchandrag <https://github.com/revanthchandrag> Updates on the login
form ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/RohitB97/saarang-portals/issues/4#issuecomment-306002127>,
or mute the thread

**Comment by RohitB97** [comment]
Come up with a good design by tonight

**Comment by revanthchandrag** [comment]
https://w3layouts.com/preview/?l=/ribbon-login-form-
responsive-widget-template/
http://p.w3layouts.com/demos/golden_login_form/web/#
https://codepen.io/andytran/full/RPBdgM
https://codepen.io/maggiben/full/KwdeaM
https://w3layouts.com/preview/?l=/simple-login-signup-form-
flat-responsive-widget-template/
https://w3layouts.com/preview/?l=/lucid-login-form-
responsive-widget-template/
https://codepen.io/dervondenbergen/pen/GCakj
https://codepen.io/boudra/full/YXzLBN

**Comment by revanthchandrag** [comment]
https://w3layouts.com/preview/?l=/ribbon-login-form-responsive-widget-template/
i liked this most

**Comment by RohitB97** [comment]
@revanthchandrag go with this - https://codepen.io/andytran/full/RPBdgM

We'll use the ribbon form in the main website....right now we can't use it..because portals shouldn't have any background

**Comment by RohitB97** [comment]
@revanthchandrag **DO this - https://codepen.io/boudra/pen/YXzLBN**
The previous form i mentioned has its code in **pug and sass ( we use HTML and CSS)** so go with this form. And use the same form for sign up also (change the fields and buttons accordingly).
